config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  devise_for :users
  resources :users, only: [:show]
  resources :rooms, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  #無記入投稿とエンター長押し連続投稿を防ぐ
  #validates :text, presence: true
  #MessageBroadcastJobを走らせるタイミングはMessageがcreateされた後
  after_create_commit {MessageBroadcastJob.perform_later self}
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :room_users, dependent: :destroy
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # アソシエーション
  has_many :messages, dependent: :destroy
  has_many :room_users, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def create
    @room = Room.create
    # RoomUserを2つ作る
    # 自分のRoomUserを作る
    @join_current_user = RoomUser.create(user_id: current_user.id, room_id: @room.id)
    # 相手のRoomUserを作る
    @join_user = RoomUser.create(join_room_params)
    redirect_to room_path(@room)
  end

  def show
    @room = Room.find(params[:id])
    #roomに関するRoomUserが存在していれば
    if RoomUser.where(user_id: current_user.id, room_id: @room.id).present?
      #アソシエーションで引っ張り出せる
      @messages = @room.messages
      @message = Message.new
      @room_users = @room.room_users
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def join_room_params
    params.require(:room_user).permit(:user_id, :room_id).merge(room_id: @room.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @current_user_room_user = RoomUser.where(user_id: current_user.id)
    @user_room_user = RoomUser.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_room_user.each do |cu|
        @user_room_user.each do |u|
          if cu.room_id == u.room_id then
            @is_room = true
            @room_id = cu.room_id
          end
        end
      end
    
      unless @is_room
        @room = Room.new
        @room_user = RoomUser.new
      end
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionCable2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %> 
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
    <div>
      <%= message.text %>
      <%= message.user.name %>
      <%= message.created_at.strftime("%Y-%m-%d %H:%M") %>
    </div>

app/views/rooms/show.html.erb
<h1>ルーム詳細ページ</h1>
  <h2>参加者</h2>
    <!-- roomに入っているroom_userは2人いるのでeachで引っ張る -->
    <% @room_users.each do |e| %>
      <%= link_to e.user.name, user_path(e.user_id) %>
    <% end %>
  <h2>トーク</h2>
    <!-- 入力フォーム -->
    <!-- form_withだと余計なものが生成されるので<form>タグで実装 -->
    <!-- room_channel.rbにroom_idとuser_idを渡す -->
    <div id="message" data-room_id="<%= params[:id] %>" data-user_id="<%= current_user.id %>">
      <form>
        <!-- message createはroom_channel.rbで行われるのでここで値を渡しても意味がない -->
        <input type="text" data-behavior="room_speak">
      </form>
    </div>

    <!-- メッセージ表示 -->
    <% if @messages.present? %>
    <div id="messages_all">
    <% @messages.each do |message| %>
      <%= render 'messages/message', message: message %>
    <% end %>
    </div>
    <% end %>

app/views/users/index.html.erb
<h1>ユーザー一覧ページ</h1>
  <% @users.each do |user| %>
    <%= link_to user.name, user_path(user.id) %>
  <% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細ページ</h1>
<h2>ユーザー名</h2>
  <%= @user.name %>
<h2>トーク関連</h2>
<% unless @user.id == current_user.id %>
  <% if @is_room == true %>
    <%= link_to "トークを始める", room_path(@room_id) %>
  <% else %>
    <!-- roomsテーブルに情報を送信 -->
    <%= form_with model: @room, local: true do |f|%>
    <!-- room_usersテーブルに情報を送信 -->
      <%= hidden_field_tag 'room_user[user_id]', @user.id %>
      <%= f.submit "チャットを始める", class: "send" %>
    <% end %>
  <% end %>
<% end %>